/* Conversation settings UI. Applying is owned by app.js so this file never starts audio or APIs. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), labels={
    ja:{title:'話し方・声・言語',help:'設定を読み込むまで編集できません。保存だけでは会話、マイク、API利用を開始しません。',load:'設定を読み込む',language:'言語',voice:'声',persona:'話し方',custom:'話し方の説明',note:'話し方は表現だけを変えます。安全機能や操作権限は変わりません。',apply:'会話を終了して設定を適用',applied:'適用しました。次の「話しかける」で使います。'},
    en:{title:'Style, voice, and language',help:'Load settings before editing. Saving does not start a conversation, microphone, or API use.',load:'Load settings',language:'Language',voice:'Voice',persona:'Speaking style',custom:'Describe the style',note:'Speaking style changes expression only. It does not change safety or control permissions.',apply:'End conversation and apply settings',applied:'Applied. It will be used the next time you talk.'}
  };
  const personaLabels={ja:{friendly:'親しみやすい',curious:'好奇心いっぱい',calm:'おだやか',custom:'カスタム'},en:{friendly:'Friendly',curious:'Curious',calm:'Calm',custom:'Custom'}};
  const stringList=value=>Array.isArray(value)&&value.length>0&&value.length<=64&&value.every(item=>typeof item==='string'&&item.length>0&&item.length<=80)&&new Set(value).size===value.length;
  const validOptions=value=>value&&typeof value==='object'&&stringList(value.languages)&&stringList(value.voices)&&stringList(value.personas)&&value.languages.every(language=>language==='ja'||language==='en')&&value.personas.every(persona=>['friendly','curious','calm','custom'].includes(persona))&&value.maxPersonaTextLength===800;
  const validState=(value,revision)=>value&&typeof value==='object'&&Object.keys(value).length===4&&['language','voice','persona','personaText'].every(key=>Object.hasOwn(value,key))&&['ja','en'].includes(value.language)&&typeof value.voice==='string'&&['friendly','curious','calm','custom'].includes(value.persona)&&typeof value.personaText==='string'&&Array.from(value.personaText).length<=800&&Number.isSafeInteger(revision)&&revision>=0;
  class FlySettings {
    constructor({connect,apply,onBusy,onLanguage}) {
      this._connect=connect;this._apply=apply;this._onBusy=onBusy;this._onLanguage=onLanguage;this._busy=false;this._options=null;this._server=null;this._baseline=null;this._dirty=false;this._wait=null;
      this._fields=$('conversation-settings-fields');this._load=$('conversation-settings-load');this._language=$('conversation-language');this._voice=$('conversation-voice');this._persona=$('conversation-persona');this._custom=$('conversation-persona-custom');this._text=$('conversation-persona-text');this._applyButton=$('conversation-settings-apply');this._status=$('conversation-settings-status');this._error=$('conversation-settings-error');
      this._load.onclick=()=>{void this.connect().catch(()=>{});};this._applyButton.onclick=()=>{void this.apply(this._draft()).catch(()=>{});};
      for(const element of [this._language,this._voice,this._persona,this._text]) element.addEventListener('input',()=>this._edited());
      this._persona.addEventListener('change',()=>{this._custom.hidden=this._persona.value!=='custom';this._edited();});
      this._renderLanguage('ja');this._setEnabled();
    }
    get busy(){return this._busy;}
    _setBusy(value){this._busy=value;this._onBusy(Boolean(value));this._setEnabled();}
    _setError(message=''){this._error.textContent=message;}
    _ready(){return Boolean(this._options&&this._server);}
    _setEnabled(){const enabled=this._ready()&&!this._busy&&!this._dirtyConflict&&!this._invalid;for(const element of [this._language,this._voice,this._persona,this._text])element.disabled=!enabled;this._applyButton.disabled=!enabled;this._load.disabled=this._busy;}
    _renderLanguage(language){const copy=labels[language]||labels.ja;$('conversation-settings-title').textContent=copy.title;$('conversation-settings-help').textContent=copy.help;this._load.textContent=copy.load;$('conversation-language-label').textContent=copy.language;$('conversation-voice-label').textContent=copy.voice;$('conversation-persona-label').textContent=copy.persona;$('conversation-persona-text-label').textContent=copy.custom;$('conversation-persona-note').textContent=copy.note;this._applyButton.textContent=copy.apply;for(const option of this._persona.options)option.textContent=(personaLabels[language]||personaLabels.ja)[option.value]||option.value;}
    _edited(){this._dirty=true;this._dirtyConflict=false;this._setError('');this._status.textContent=this._language.value==='en'?'Changes have not been applied.':'未適用の変更があります。';this._custom.hidden=this._persona.value!=='custom';this._renderLanguage(this._language.value);this._updateCount();this._setEnabled();}
    _updateCount(){const count=Array.from(this._text.value).length;$('conversation-persona-count').textContent=String(count);}
    _populate(select,values,label){select.replaceChildren(...values.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=label(value);return option;}));}
    _settingsValid(settings){if(!validState(settings,this._server?.revision))return false;return this._options.languages.includes(settings.language)&&this._options.voices.includes(settings.voice)&&this._options.personas.includes(settings.persona)&&Array.from(settings.personaText).length<=this._options.maxPersonaTextLength;}
    _sync(){if(!this._ready()||this._dirty)return;const {settings,revision}=this._server;if(this._baseline?.revision===revision&&!this._fields.hidden&&JSON.stringify(this._baseline.settings)===JSON.stringify(settings)){this._finishWait();return;}this._invalid=!this._settingsValid(settings);this._baseline={settings:{...settings},revision};if(this._invalid){this._setError('Bridgeから認識できない会話設定を受信しました。設定を適用できません。');this._setEnabled();return;}
      this._populate(this._language,this._options.languages,value=>value==='ja'?'日本語':'English');this._populate(this._voice,this._options.voices,value=>value);this._populate(this._persona,this._options.personas,value=>personaLabels.ja[value]||value);this._language.value=settings.language;this._voice.value=settings.voice;this._persona.value=settings.persona;this._text.value=settings.personaText;$('conversation-persona-max').textContent=String(this._options.maxPersonaTextLength);this._custom.hidden=settings.persona!=='custom';this._updateCount();this._renderLanguage(settings.language);this._fields.hidden=false;this._setError('');this._setEnabled();this._finishWait();
    }
    _finishWait(){if(this._wait&&this._ready()&&!this._invalid){clearTimeout(this._wait.timer);this._wait.resolve();this._wait=null;}}
    _clear(){this._options=null;this._server=null;this._baseline=null;this._dirty=false;this._dirtyConflict=false;this._invalid=false;this._fields.hidden=true;this._status.textContent='';this._setError('');this._setEnabled();}
    async connect(){if(this.busy)return;if(typeof this._connect!=='function')throw new Error('設定接続を開始できません。');this._baseline=null;this._dirty=false;this._dirtyConflict=false;this._invalid=false;this._status.textContent='';this._setError('');this._setBusy(true);let waiter=null;try{await this._connect();this._sync();if(!this._ready()||this._invalid){await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(this._wait===waiter){this._wait=null;reject(new Error('Bridgeから会話設定を取得できませんでした。旧Bridgeはこの設定に対応していない可能性があります。'));}},2500);waiter={resolve,reject,timer};this._wait=waiter;this._finishWait();});this._sync();}this._status.textContent='現在の設定を読み込みました。';}catch(error){this._setError(error?.message||'設定を読み込めませんでした。');throw error;}finally{if(waiter&&this._wait===waiter){clearTimeout(waiter.timer);this._wait=null;}this._setBusy(false);}}
    receive(msg){if(!msg||typeof msg.type!=='string')return;if(msg.type==='conversation_options'){if(!validOptions(msg)){this._invalid=true;this._setError('Bridgeから会話設定の選択肢を正しく取得できませんでした。');this._setEnabled();return;}this._options={languages:[...msg.languages],voices:[...msg.voices],personas:[...msg.personas],maxPersonaTextLength:msg.maxPersonaTextLength};if(!this._dirty)this._baseline=null;this._sync();return;}
      if(msg.type==='bridge_state'&&Object.hasOwn(msg,'conversationSettings')){if(!validState(msg.conversationSettings,msg.conversationSettingsRevision)){this._invalid=true;this._setError('Bridgeから認識できない会話設定を受信しました。設定を適用できません。');this._setEnabled();return;}const incoming={settings:{...msg.conversationSettings},revision:msg.conversationSettingsRevision};if(this._server&&incoming.revision<this._server.revision)return;this._server=incoming;this._onLanguage(incoming.settings.language);if(this._dirty&&this._baseline&&incoming.revision!==this._baseline.revision){this._dirtyConflict=true;this._setError('ほかの場所で設定が変更されました。「設定を読み込む」で最新の設定を確認してください。');this._setEnabled();return;}this._sync();}
    }
    disconnect(){this._clear();}
    _draft(){const persona=this._persona.value,raw=this._text.value,personaText=persona==='custom'?raw.trim():'';return {settings:{language:this._language.value,voice:this._voice.value,persona,personaText},expectedRevision:this._baseline?.revision};}
    _validateDraft(draft){if(!this._baseline||draft.expectedRevision!==this._baseline.revision)throw new Error('設定を読み込み直してから適用してください。');const text=draft.settings?.personaText;if(typeof text==='string'&&Array.from(text).length>this._options.maxPersonaTextLength)throw new Error('話し方の説明は800文字以内にしてください。');if(!this._settingsValid(draft.settings))throw new Error('設定を読み込み直してから適用してください。');if(/[\u0000-\u0008\u000B-\u001F\u007F-\u009F]/.test(text))throw new Error('話し方の説明には改行とタブ以外の制御文字を使えません。');if(draft.settings.persona==='custom'&&!text)throw new Error('カスタムの話し方を説明してください。');}
    async apply(draft){if(this.busy)return;try{this._validateDraft(draft);this._setBusy(true);const result=await this._apply(draft);if(!result||result.requiresExplicitStart!==true||!validState(result.settings,result.revision)||!this._settingsValid(result.settings))throw new Error('Bridgeから適用結果を正しく確認できませんでした。');this._server={settings:{...result.settings},revision:result.revision};this._baseline=null;this._dirty=false;this._dirtyConflict=false;this._invalid=false;this._sync();this._status.textContent=(labels[result.settings.language]||labels.ja).applied;this._onLanguage(result.settings.language);return result;}catch(error){this._setError(error?.message||'設定を適用できませんでした。');throw error;}finally{this._setBusy(false);}}
  }
  window.FlySettings=FlySettings;
})();
